variables:
  VERSION_ID: '1.0.$CI_PIPELINE_ID'

stages:
  - build
  
build:
  image: electronuserland/builder:wine
  stage: build
  script:
    - yarn && yarn electron:build
    - curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file $CI_PROJECT_DIR/dist_electron/*.exe ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/toothy-tron/${VERSION_ID}/toothy-tron-setup.exe

