variables:
  VERSION_ID: '1.0.$CI_PIPELINE_ID'

stages:
  - build
  
build:
  image: electronuserland/builder:wine
  stage: build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist_electron/*.*
  script:
    - sed "s/0.0.0/${VERSION_ID}/g" package.json > _package.json && mv _package.json package.json
    - yarn && yarn electron:build
